/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Helen (https://sketchfab.com/helen_k)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/jar-of-hearts-678bc5e8d88240678e929391e94d593a
title: Jar of Hearts
*/

import React, { useRef } from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/model2Draco.gltf");
  const ref = useRef();
  useFrame((state, delta) => (ref.current.rotation.y += 0.01));
  return (
    <group {...props} dispose={null} ref={ref}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Heart_UVlambert2SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Heart_UVlambert2SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.lambert2SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.lambert4SG} />
      </group>
    </group>
  );
}

useGLTF.preload("/model2Draco.gltf");
