/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Pastore Gonzalez (https://sketchfab.com/Pastore.Gonzalez)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/heart-in-a-bottle-2ff0a8b162a74f568cd5fdcf2cbce741
title: Heart in a Bottle
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {

  const { nodes, materials } = useGLTF("/modelDraco.gltf");
  const ref = useRef();
  useFrame((state, delta) => (ref.current.rotation.y += 0.01));

  return (
    <group {...props} dispose={null} scale={0.005} ref={ref}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-54.06, -99.87, -32.54]} rotation={[-Math.PI / 2, 0, 0]} scale={9.83}>
            <mesh geometry={nodes.Burbujas_2_Burbujas_0.geometry} material={materials.Burbujas} />
            <mesh geometry={nodes.Burbujas_2_Burbujas_0_1.geometry} material={materials.Burbujas} />
            <mesh geometry={nodes.Burbujas_2_Burbujas_0_2.geometry} material={materials.Burbujas} />
            <mesh geometry={nodes.Burbujas_2_Burbujas_0_3.geometry} material={materials.Burbujas} />
            <mesh geometry={nodes.Burbujas_2_Burbujas_0_4.geometry} material={materials.Burbujas} />
            <mesh geometry={nodes.Burbujas_2_Burbujas_0_5.geometry} material={materials.Burbujas} />
            <mesh geometry={nodes.Burbujas_2_Burbujas_0_6.geometry} material={materials.Burbujas} />
          </group>
          <group position={[0, -9.3, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={133.58}>
            <mesh geometry={nodes.Liquido_2_Agua_2_0.geometry} material={materials.Agua_2} />
            <mesh geometry={nodes.Liquido_2_Agua_2_0_1.geometry} material={materials.Agua_2} />
          </group>
          <group position={[-55.62, -92.85, -32.54]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={9.83}>
            <mesh geometry={nodes.Burbujas_1_Burbujas_0.geometry} material={materials.Burbujas} />
            <mesh geometry={nodes.Burbujas_1_Burbujas_0_1.geometry} material={materials.Burbujas} />
            <mesh geometry={nodes.Burbujas_1_Burbujas_0_2.geometry} material={materials.Burbujas} />
            <mesh geometry={nodes.Burbujas_1_Burbujas_0_3.geometry} material={materials.Burbujas} />
            <mesh geometry={nodes.Burbujas_1_Burbujas_0_4.geometry} material={materials.Burbujas} />
            <mesh geometry={nodes.Burbujas_1_Burbujas_0_5.geometry} material={materials.Burbujas} />
          </group>
          <group position={[0, -9.3, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={133.58}>
            <mesh geometry={nodes.Liquido_1_Agua_1_0.geometry} material={materials.Agua_1} />
            <mesh geometry={nodes.Liquido_1_Agua_1_0_1.geometry} material={materials.Agua_1} />
          </group>
          <group position={[0, 4.81, -0.66]} scale={56.11}>
            <mesh geometry={nodes.Corazon_Corazon_0.geometry} material={materials.Corazon} />
            <mesh geometry={nodes.Corazon_Corazon_0_1.geometry} material={materials.Corazon} />
          </group>
          <group position={[0, 4.81, -0.66]} scale={56.11}>
            <mesh geometry={nodes["Boca_+_Ojos_Material001_0"].geometry} material={materials["Material.001"]} />
          </group>
          <group position={[0, -8.05, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={148.42}>
            <mesh geometry={nodes.Botella_Cristal_0.geometry} material={materials.Cristal} />
            <mesh geometry={nodes.Botella_Cristal_0_1.geometry} material={materials.Cristal} />
            <mesh geometry={nodes.Botella_Cristal_0_2.geometry} material={materials.Cristal} />
            <mesh geometry={nodes.Botella_Cristal_0_3.geometry} material={materials.Cristal} />
            <mesh geometry={nodes.Botella_Cristal_0_4.geometry} material={materials.Cristal} />
            <mesh geometry={nodes.Botella_Cristal_0_5.geometry} material={materials.Cristal} />
            <mesh geometry={nodes.Botella_Cristal_0_6.geometry} material={materials.Cristal} />
            <mesh geometry={nodes.Botella_Cristal_0_7.geometry} material={materials.Cristal} />
            <mesh geometry={nodes.Botella_Cristal_0_8.geometry} material={materials.Cristal} />
            <mesh geometry={nodes.Botella_Cristal_0_9.geometry} material={materials.Cristal} />
            <mesh geometry={nodes.Botella_Cristal_0_10.geometry} material={materials.Cristal} />
            <mesh geometry={nodes.Botella_Cristal_0_11.geometry} material={materials.Cristal} />
            <mesh geometry={nodes.Botella_Cristal_0_12.geometry} material={materials.Cristal} />
          </group>
          <group position={[0, 216.88, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[37.87, 37.87, 26.87]}>
            <mesh geometry={nodes.Corcho_Corcho_0.geometry} material={materials.Corcho} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/modelDraco.gltf");
